name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # Change to 'main' if your default branch is 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Verify gunicorn installation
      run: |
        pip install gunicorn
        pip freeze | grep gunicorn

    - name: Create necessary directories
      run: |
        mkdir -p uploads
        mkdir -p schema_uploads
        mkdir -p traces
        touch uploads/.gitkeep
        touch schema_uploads/.gitkeep
        touch traces/.gitkeep

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'esb-transformer-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .

    - name: Configure App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: 'esb-transformer-app'
        app-settings-json: |
          [
            {
              "name": "WEBSITES_PORT",
              "value": "5000",
              "slotSetting": false
            },
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true",
              "slotSetting": false
            },
            {
              "name": "FLASK_APP",
              "value": "app.py",
              "slotSetting": false
            }
          ]
        general-settings-json: |
          {
            "linuxFxVersion": "PYTHON|3.10",
            "appCommandLine": "gunicorn --bind=0.0.0.0 --timeout 600 app:app"
          }
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }} 